import { Smartphone, Tablet } from "lucide-react";
import type { DeviceType } from "../../../types";

export const devices: DeviceType[] = [
    // {
    //   id: "pixel-6",
    //   name: "Google Pixel 6",
    //   type: "android",
    //   category: "Phone",
    //   icon: Smartphone,
    //   width: 322,
    //   height: 670,
    //   popular: false,
    //   imageUrl: "/frames/pixel.png",
    //   rx: 55,
    //   ry: 55,
    //   dimensions: "1179 x 2556",
    // },
    {
        id: "samsung-galaxy-s10",
        name: "Samsung Galaxy S10",
        type: "android",
        category: "Phone",
        icon: Smartphone,
        width: 360,
        height: 760,
        popular: false,
        rx: 55,
        ry: 55,
        dimensions: "1440 x 3040",
        imageUrl: "/frames/samsungS10.png",
    },
    {
        id: "iphone-11",
        name: "iphone 11",
        type: "iphone",
        category: "Phone",
        icon: Smartphone,
        width: 322,
        height: 670,
        popular: false,
        imageUrl: "/frames/iphone.png",
        rx: 55,
        ry: 55,
        dimensions: "828 x 1792",
    },
    {
        id: "samsung-galaxy-s21",
        name: "Samsung Galaxy S21",
        type: "android",
        category: "Phone",
        icon: Smartphone,
        width: 1080,
        height: 2390,
        rx: 55,
        ry: 55,
        popular: false,
        imageUrl: "/frames/samsung-galaxy-black.png",
        dimensions: "1080 x 2400",
    },
    // {
    //   id: "iphone-14",
    //   name: "iPhone 14 Pro",
    //   type: "iphone",
    //   category: "Phone",
    //   icon: Smartphone,
    //   popular: true,
    //   dimensions: "1179 x 2556",
    // },
    {
        id: "iphone-16",
        name: "Iphone 16 black",
        type: "iphone",
        category: "Phone",
        width: 1315,
        height: 2870,
        rx: 95,
        ry: 95,
        icon: Smartphone,
        popular: false,
        dimensions: "1179 x 2556",
        imageUrl: "/frames/iphone-16-black.png",
    },
    {
        name: "Ipad Air 4",
        type: "tab",
        category: "Tablet",
        icon: Tablet,
        width: 505,
        height: 352,
        rx: 0,
        ry: 0,
        imageUrl: "/frames/IpadAir4.png",
    },
    // {
    //   id: "samsung-s23",
    //   name: "Samsung Galaxy S23",
    //   category: "Phone",
    //   icon: Smartphone,
    //   popular: false,
    //   dimensions: "1080 x 2340",
    // },

    {
        name: "Tecno Pova neo",
        type: "android",
        category: "Phone",
        icon: Smartphone,
        width: 249,
        height: 559,
        rx: 55,
        ry: 55,
        popular: true,
        imageUrl: "/frames/android2.png",
        dimensions: "720 x 1640",
    },
];